# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  dev:
    desc: "run go server in development mode"
    cmd: go run cmd/http/main.go

  compose:up:
    desc: "run docker containers"
    cmd: docker compose up -d

  compose:down:
    desc: "remove running docker containers"
    cmd: docker compose down

  db:cli:
    desc: "access postgres db cli"
    cmd: docker exec -it postgres psql -U {{ .DB_USER }} -b {{ .DB_NAME }}
